// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VissmaFlow.Core.Infrastructure.DataAccess;

#nullable disable

namespace VissmaFlow.Core.Migrations
{
    [DbContext(typeof(VissmaDbContext))]
    [Migration("20231213083426_add_rtk_unit")]
    partial class addrtkunit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("VissmaFlow.Core.Models.Communication.CommSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Baudrate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StopBitsNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CommSettings");
                });

            modelBuilder.Entity("VissmaFlow.Core.Models.Communication.RtkUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RtkUnits");
                });

            modelBuilder.Entity("VissmaFlow.Core.Models.Parameters.ParameterBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BitNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ByteOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Data")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxValueString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinValueString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModbRegNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModbusRegType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StrLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParameterBases");
                });
#pragma warning restore 612, 618
        }
    }
}
